// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeMirror: typeof import('./../../../src/components/base/CodeMirror/CodeMirror.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    OlpHeaderMenu: typeof import('./../../../src/components/common/olp-header-menu/OlpHeaderMenu.vue')['default']
    OlpMarkdownEdit: typeof import('./../../../src/components/base/OlpMarkdownEdit/OlpMarkdownEdit.vue')['default']
    OlpMenuButton: typeof import('./../../../src/components/common/olp-header-menu/olp-menu-button/OlpMenuButton.vue')['default']
    OlpMenuItem: typeof import('./../../../src/components/common/olp-header-menu/olp-menu-item/OlpMenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeleportToBody: typeof import('./../../../src/components/base/TeleportToBody/TeleportToBody.vue')['default']
  }
}

export {}
