/*
 * @Author: ND_LJQ
 * @Date: 2022-04-28 14:42:47
 * @LastEditors: ND_LJQ
 * @LastEditTime: 2022-04-28 14:59:40
 * @Description:
 * @Email: ndliujunqi@outlook.com
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
    }
}

export {};
